[package]
name = "solana-malleability-tester"
version = "1.0.0"
edition = "2021"
authors = ["Your Name <your.email@example.com>"]
description = "Enhanced Ed25519 Signature Malleability Tester for Solana Devnet"
license = "MIT"
keywords = ["solana", "cryptography", "ed25519", "malleability", "security"]

[[bin]]
name = "malleability_tester"
path = "src/main.rs"

[dependencies]
# Solana SDK dan client libraries
solana-sdk = "1.17"
solana-client = "1.17"

# Cryptography
ed25519-dalek = { version = "2.0", features = ["rand_core"] }
curve25519-dalek = "4.0"

# Async runtime
tokio = { version = "1.0", features = ["full"] }

# Error handling
anyhow = "1.0"

# Logging
log = "0.4"
env_logger = "0.10"

# Data serialization dan CSV
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
csv = "1.3"

# HTTP client untuk custom RPC calls
reqwest = { version = "0.11", features = ["json"] }

# Utilities
chrono = { version = "0.4", features = ["serde"] }
hex = "0.4"
rand = "0.8"

# Optional: untuk pretty printing dan debug
colored = "2.0"
indicatif = "0.17"

[dev-dependencies]
# Testing utilities
tokio-test = "0.4"